# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# example AWS instance
---
tenant: svx-ProdA
project: keller
cloud: aws
domain: production
application: postgresql
region: ap-southeast-2
cluster: a
replica: no
role: none
dataflow: none
user: centos
ami: ami-34171d57
type: t2.micro
root_volume: 11
data_volume: 20
cidr_block: 10.103.2.0/23
interface_subnet: 10.103.2.128/26
count: 1
interface_acl: postgresql