#!/bin/sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 

export AWS_PROFILE=datanexus    # set this to the desired AWS profile in ~/.aws/credentials

if [ "$1" == "-h" ] ; then
    echo "Usage:  `basename $0` [-h]\t\thelp"
    echo "\t`basename $0` [aws | osp]\tuse either the aws or osp configuration file"
    exit 0
fi

if [ $1 == "aws" ]; then
  export cloud=aws
elif [ $1 == "osp" ]; then
  export cloud=osp
fi

./initialize -e "configuration=$cloud-configuration.yml"
echo "running with $cloud configuration..."
./provision-postgresql -e "configuration=$cloud-configuration.yml"
